export const KNOWN_PHRASES = [
  // Sauces & Condiments
  "soy sauce",
  "fish sauce",
  "oyster sauce",
  "hoisin sauce",
  "hot sauce",
  "chili sauce",
  "sweet chili sauce",
  "tomato sauce",
  "spaghetti sauce",
  "barbecue sauce",
  "bbq sauce",
  "worcestershire sauce",
  "teriyaki sauce",
  "steak sauce",
  "hot pepper sauce",
  "chili garlic sauce",
  "banana ketchup",
  "tomato ketchup",
  "shrimp paste",
  "bagoong alamang",
  "bagoong isda",
  "peanut butter",
  "coconut aminos",

  // Vinegars
  "white vinegar",
  "cane vinegar",
  "coconut vinegar",
  "apple cider vinegar",
  "rice vinegar",
  "rice wine vinegar",
  "red wine vinegar",
  "white wine vinegar",
  "balsamic vinegar",

  // Oils & Fats
  "olive oil",
  "extra virgin olive oil",
  "vegetable oil",
  "coconut oil",
  "canola oil",
  "sesame oil",
  "peanut oil",
  "corn oil",
  "sunflower oil",
  "cooking oil",
  "chili oil",
  "garlic oil",
  "pork fat",
  "chicken fat",
  "unsalted butter",
  "salted butter",

  // Meat - Pork
  "ground pork",
  "pork belly",
  "pork shoulder",
  "pork loin",
  "pork chop",
  "pork chops",
  "pork ribs",
  "pork tenderloin",
  "pork hock",
  "pork leg",
  "pork knuckle",
  "pork liver",
  "pork blood",
  "pork intestines",

  // Meat - Beef
  "ground beef",
  "beef brisket",
  "beef chuck",
  "beef shank",
  "beef ribs",
  "beef short ribs",
  "beef sirloin",
  "beef tenderloin",
  "beef steak",
  "beef tripe",
  "beef liver",
  "beef broth",
  "beef stock",

  // Chicken & Poultry
  "chicken breast",
  "chicken thigh",
  "chicken thighs",
  "chicken wings",
  "chicken leg",
  "chicken legs",
  "chicken drumsticks",
  "chicken liver",
  "chicken feet",
  "whole chicken",
  "ground chicken",
  "chicken broth",
  "chicken stock",

  // Seafood
  "fish fillet",
  "fish fillets",
  "white fish",
  "milk fish",
  "milkfish belly",
  "smoked fish",
  "dried fish",
  "salted fish",
  "tuna flakes",
  "tuna steak",
  "crab meat",
  "crab sticks",
  "shrimp paste",
  "dried shrimp",
  "baby squid",

  // Rice & Grains
  "white rice",
  "brown rice",
  "jasmine rice",
  "glutinous rice",
  "sticky rice",
  "cooked rice",
  "day old rice",
  "rice flour",
  "glutinous rice flour",
  "corn starch",
  "cornstarch",
  "all purpose flour",
  "whole wheat flour",
  "bread flour",
  "cake flour",

  // Noodles
  "rice noodles",
  "egg noodles",
  "glass noodles",
  "vermicelli noodles",
  "rice vermicelli",
  "sotanghon noodles",
  "bihon noodles",
  "canton noodles",
  "pancit canton",
  "pancit bihon",
  "instant noodles",

  // Vegetables
  "red onion",
  "white onion",
  "green onion",
  "spring onion",
  "green onions",
  "spring onions",
  "green beans",
  "string beans",
  "yardlong beans",
  "mung beans",
  "bean sprouts",
  "green peas",
  "snow peas",
  "sweet potato",
  "sweet potatoes",
  "baby potatoes",
  "bok choy",
  "pechay baguio",
  "napa cabbage",
  "chinese cabbage",
  "green cabbage",
  "red cabbage",
  "bell pepper",
  "bell peppers",
  "red bell pepper",
  "green bell pepper",
  "yellow bell pepper",
  "chili pepper",
  "chili peppers",
  "green chili",
  "red chili",
  "chili flakes",
  "red pepper flakes",
  "black beans",
  "banana blossom",
  "bamboo shoots",
  "water spinach",
  "bitter melon",
  "bottle gourd",
  "sponge gourd",
  "chayote squash",

  // Garlic, Ginger & Aromatics
  "garlic cloves",
  "garlic clove",
  "garlic powder",
  "onion powder",
  "ginger root",
  "ginger powder",
  "lemon grass",
  "lemon grass stalk",
  "lemongrass stalk",
  "bay leaf",
  "bay leaves",
  "pandan leaves",
  "pandan leaf",

  // Herbs & Spices
  "black pepper",
  "black peppercorns",
  "white pepper",
  "ground pepper",
  "ground black pepper",
  "ground white pepper",
  "whole peppercorns",
  "cayenne pepper",
  "paprika powder",
  "smoked paprika",
  "chili powder",
  "curry powder",
  "garlic powder",
  "onion powder",
  "five spice",
  "five spice powder",
  "star anise",
  "cinnamon stick",
  "cinnamon sticks",
  "cinnamon powder",

  // Sugar & Sweeteners
  "white sugar",
  "brown sugar",
  "dark brown sugar",
  "light brown sugar",
  "coconut sugar",
  "palm sugar",
  "powdered sugar",
  "confectioners sugar",
  "icing sugar",
  "maple syrup",
  "corn syrup",

  // Dairy
  "whole milk",
  "fresh milk",
  "evaporated milk",
  "condensed milk",
  "sweetened condensed milk",
  "coconut milk",
  "coconut cream",
  "heavy cream",
  "heavy whipping cream",
  "whipping cream",
  "all purpose cream",
  "cream cheese",
  "cheddar cheese",
  "parmesan cheese",
  "mozzarella cheese",

  // Eggs
  "egg yolk",
  "egg yolks",
  "egg white",
  "egg whites",
  "hard boiled egg",
  "hard boiled eggs",
  "salted egg",
  "salted eggs",

  // Baking
  "baking powder",
  "baking soda",
  "vanilla extract",
  "vanilla essence",
  "cocoa powder",
  "dark chocolate",
  "milk chocolate",
  "white chocolate",
  "chocolate chips",
  "bread crumbs",
  "bread crumbs",
  "panko breadcrumbs",

  // Canned / Packaged
  "tomato paste",
  "tomato puree",
  "canned tomatoes",
  "diced tomatoes",
  "crushed tomatoes",
  "pineapple chunks",
  "pineapple juice",
  "fruit cocktail",
  "canned tuna",
  "corned beef",
  "coconut water",

  // Fruits
  "green mango",
  "ripe mango",
  "ripe banana",
  "saba banana",
  "calamansi juice",
  "lemon juice",
  "lime juice",
  "orange juice",
  "pineapple juice",
  "lemon zest",
  "lime zest",
  "orange zest",

  // Filipino-specific ingredients
  "calamansi juice",
  "siling labuyo",
  "siling haba",
  "siling pangsigang",
  "banana ketchup",
  "liver spread",
  "liver sauce",
  "annatto seeds",
  "annatto powder",
  "atsuete seeds",
  "atsuete powder",
  "ube halaya",
  "ube extract",
  "ube flavoring",
  "young coconut",
  "young coconut strips",
  "macapuno strings",
  "nata de coco",
  "kaong",
  "sago pearls",
  "tapioca pearls",
  "gulaman powder",
  "pandan extract",
  "pandan leaves",
  "malagkit rice",
  "malagkit flour",
  "gata ng niyog",
  "kakang gata",
  "tinapa flakes",
  "tuyo flakes",
  "longganisa sausage",
  "tocino meat",
  "kesong puti",

  // Stocks / Broths / Seasonings
  "chicken stock",
  "chicken broth",
  "beef stock",
  "beef broth",
  "pork stock",
  "pork broth",
  "vegetable stock",
  "vegetable broth",
  "bouillon cube",
  "chicken bouillon",
  "beef bouillon",
  "seasoning sauce",

  // Common multi-word cooking ingredients
  "ice cubes",
  "cold water",
  "warm water",
  "hot water",
  "boiling water",
  "sea salt",
  "kosher salt"
];